version: 2
project_name: goswaggen

before:
  hooks:
    - go mod tidy

builds:
  - id: cli
    main: ./main.go
    binary: goswaggen
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/ysmnababan/goswaggen/internal/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        formats: [zip]

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
      - "^style:"
      - "^refactor:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: "🚀 New Features"
      regexp: "^feat"
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: "^fix"
      order: 1
    - title: "⚙️ Other Changes"
      order: 999

release:
  footer: |
    See [CHANGELOG.md](https://github.com/ysmnababan/goswaggen/blob/master/CHANGELOG.md) for full details.
