package framework

var IMPORT_PATH_VALUE = map[string]string{
	"echo": "github.com/labstack/echo/v4",
}

var OBJECT_TYPE_IMPORT = map[string]string{
	"ECHO":       "*github.com/labstack/echo/v4.Echo",
	"ECHO_GROUP": "*github.com/labstack/echo/v4.Group",
}
var ECHO_VARIABLE_TYPE = "*github.com/labstack/echo/v4.Echo"
var ECHO_GROUP_VARIABLE_TYPE = "*github.com/labstack/echo/v4.Group"
var ECHO_CONTEXT_TYPE = "github.com/labstack/echo/v4.Context"

var ECHO_REQUEST_DATA_METHOD = map[string]bool{
	"Bind":       true,
	"QueryParam": true,
	"Param":      true,
}

// Map for echo response with tuple of param position.
// {<status_code>, <payload>}
// 0 : no param
//
// n : data is in n-th param, etc
var ECHO_FRAMEWORK_STANDARD_RESPONSE = map[string][2]int{
	"String":     {1, 2},
	"HTML":       {1, 2},
	"HTMLBlob":   {1, 2},
	"JSON":       {1, 2},
	"JSONPretty": {1, 2},
	"JSONBlob":   {1, 2},
	"JSONP":      {1, 2},
	"XML":        {1, 2},
	"XMLPretty":  {1, 2},
	"XMLBlob":    {1, 2},
	"File":       {0, 0},
	"Attachment": {0, 0},
	"Inline":     {0, 0},
	"Blob":       {1, 2},
	"Stream":     {1, 2},
	"NoContent":  {1, 0},
	"Redirect":   {1, 0},
}

var HTTP_STATUS_CODE_MAPPING = map[string]int{
	"StatusContinue":                      100,
	"100":                                 100,
	"StatusSwitchingProtocols":            101,
	"101":                                 101,
	"StatusProcessing":                    102,
	"102":                                 102,
	"StatusEarlyHints":                    103,
	"103":                                 103,
	"StatusOK":                            200,
	"200":                                 200,
	"StatusCreated":                       201,
	"201":                                 201,
	"StatusAccepted":                      202,
	"202":                                 202,
	"StatusNonAuthoritativeInfo":          203,
	"203":                                 203,
	"StatusNoContent":                     204,
	"204":                                 204,
	"StatusResetContent":                  205,
	"205":                                 205,
	"StatusPartialContent":                206,
	"206":                                 206,
	"StatusMultiStatus":                   207,
	"207":                                 207,
	"StatusAlreadyReported":               208,
	"208":                                 208,
	"StatusIMUsed":                        226,
	"226":                                 226,
	"StatusMultipleChoices":               300,
	"300":                                 300,
	"StatusMovedPermanently":              301,
	"301":                                 301,
	"StatusFound":                         302,
	"302":                                 302,
	"StatusSeeOther":                      303,
	"303":                                 303,
	"StatusNotModified":                   304,
	"304":                                 304,
	"StatusUseProxy":                      305,
	"305":                                 305,
	"StatusTemporaryRedirect":             307,
	"307":                                 307,
	"StatusPermanentRedirect":             308,
	"308":                                 308,
	"StatusBadRequest":                    400,
	"400":                                 400,
	"StatusUnauthorized":                  401,
	"401":                                 401,
	"StatusPaymentRequired":               402,
	"402":                                 402,
	"StatusForbidden":                     403,
	"403":                                 403,
	"StatusNotFound":                      404,
	"404":                                 404,
	"StatusMethodNotAllowed":              405,
	"405":                                 405,
	"StatusNotAcceptable":                 406,
	"406":                                 406,
	"StatusProxyAuthRequired":             407,
	"407":                                 407,
	"StatusRequestTimeout":                408,
	"408":                                 408,
	"StatusConflict":                      409,
	"409":                                 409,
	"StatusGone":                          410,
	"410":                                 410,
	"StatusLengthRequired":                411,
	"411":                                 411,
	"StatusPreconditionFailed":            412,
	"412":                                 412,
	"StatusRequestEntityTooLarge":         413,
	"413":                                 413,
	"StatusRequestURITooLong":             414,
	"414":                                 414,
	"StatusUnsupportedMediaType":          415,
	"415":                                 415,
	"StatusRequestedRangeNotSatisfiable":  416,
	"416":                                 416,
	"StatusExpectationFailed":             417,
	"417":                                 417,
	"StatusTeapot":                        418,
	"418":                                 418,
	"StatusMisdirectedRequest":            421,
	"421":                                 421,
	"StatusUnprocessableEntity":           422,
	"422":                                 422,
	"StatusLocked":                        423,
	"423":                                 423,
	"StatusFailedDependency":              424,
	"424":                                 424,
	"StatusTooEarly":                      425,
	"425":                                 425,
	"StatusUpgradeRequired":               426,
	"426":                                 426,
	"StatusPreconditionRequired":          428,
	"428":                                 428,
	"StatusTooManyRequests":               429,
	"429":                                 429,
	"StatusRequestHeaderFieldsTooLarge":   431,
	"431":                                 431,
	"StatusUnavailableForLegalReasons":    451,
	"451":                                 451,
	"StatusInternalServerError":           500,
	"500":                                 500,
	"StatusNotImplemented":                501,
	"501":                                 501,
	"StatusBadGateway":                    502,
	"502":                                 502,
	"StatusServiceUnavailable":            503,
	"503":                                 503,
	"StatusGatewayTimeout":                504,
	"504":                                 504,
	"StatusHTTPVersionNotSupported":       505,
	"505":                                 505,
	"StatusVariantAlsoNegotiates":         506,
	"506":                                 506,
	"StatusInsufficientStorage":           507,
	"507":                                 507,
	"StatusLoopDetected":                  508,
	"508":                                 508,
	"StatusNotExtended":                   510,
	"510":                                 510,
	"StatusNetworkAuthenticationRequired": 511,
	"511":                                 511,
}
